### ISSUE TITLE
Denkproblem im Konzept

### ISSUE THREAD

**Issue by pklaschka** [pklaschka/RGW-Q11-inf21-16-18-Projekt#4]
Ich habe eben ein Problem in unserem Konzept festgestellt:
## Das Problem
Wir hatten ja gesagt, dass man sich am Endboss direkt versuchen könnte, jedoch durch "Leveln & Looten" gut genug werden kann, um diesen zu besiegen. Gleichzeitig haben wir aber auch gesagt, dass man auch im Endlosmodus "leveln & looten" kann.
Nun stellt sich das Problem, dass man dementsprechend den Endboss besiegen könnte, bevor man auch nur ein "storyerklärendes" Level aus der Kampagne gespielt hat.
## Ein Beispiel
Zum Beispiel könnte ein Spieler beim ersten mal spielen folgende Reihenfolge gehen:

1. Versuch des Besiegens des Endbosses (scheitert)
2. Leveln im Endlosmodus
3. Besiegen des Endbosses
4. Levels durchspielen

Dabei würde der Spieler dann auf das Phänomen treffen, dass der Endboss noch lebt. Da dies etwas merkwürdig wäre, habe ich im Folgenden einige Lösungsansätze:
## Lösungsansätze

- Der Endbosskampf wird erst nach dem Spielen des ersten Levels, dass ein wenig in die Story einführt, freigeschaltet und das Durchspielen der Levels wird danach gesperrt (und kann nur durch ein Drücken auf einen Reset-Button freigeschaltet werden, dadurch verschwinden jedoch auch Fähigkeiten
- Der Endlosmodus ist ein eigenständiges Element, dessen Erfolge nicht in den Kampagnenmodus miteingehen (Problem hierbei: Dem Spieler könnte das Level, das er in den Kampagnenleveln erreicht, nicht ausreichen, um den Endboss zu besiegen).

_Falls jemand eine Meinung dazu hat, schreibt das gerne mal in die Kommentarsektion dieses Issues, gerne auch weitere Lösungsansätze etc._

## Diagramm mit aktuellem Konzept:

![Diagram](https://cloud.githubusercontent.com/assets/25147704/22560280/506be7ac-e974-11e6-93c9-c22daaad96bd.png)

**Comment by daniel1r** [comment]
Vorschlag: endlosmodus wird erst in der Story freigeschaltet. So können wir für den endlosmodus nkch ne Story einbauen, bzw. Diesen erklären

**Comment by pklaschka** [comment]
@daniel1r Gute Idee, warten wir noch, was die Anderen dazu sagen, aber im Moment würde ich sagen, das klingt vielversprechend.

**Comment by daniel1r** [comment]
Vorschlag 2: 
Dein 2. Lösungsansatz
+ schwerer Boss nach dem endboss, sodass man nachdem man das Spiel durch hat ,entweder lvl wiederholen muss oder den endlosmodus spielen muss um stärker zu werden

**Comment by daniel1r** [comment]
Das + soll ein Plus sein

**Comment by pklaschka** [comment]
@daniel1r Auch interessant, ich finde aber fast Vorschlag 1 deinerseits besser (insbesondere, da man sich dadurch das "Spielen für den Highscore" erst freispielt, in den Levels können wir noch kontrolliert einige Spielmechaniken dem Spieler erklären) ;-)

**Comment by M-Lampert** [comment]
Man könnte es auch so lösen, dass man im endlosmodus nur "unwichtige" upgrades erhalten kann und dadurch alleine nicht den boss besiegen kann. Dazu würde ich vor spielen des ersten levels natürlich endbosskampf und endlosmoyus sperren.
Beispiel für den vorschlag wäre, dass man im endlos nur leveln oder/und geld verdienen kann und damit nur verbesserung der stats oder anderes aussehen bezwecken und skills oder items wie doppelsprung oder schwert können nur in bestimmten levels gewonnen werden

**Comment by daniel1r** [comment]
@M-Lampert ich würd das mit meinem 1. Vorschlag kombinieren, dann fände ich das schon als perfekte Lösung

**Comment by pklaschka** [comment]
@daniel1r @M-Lampert Ich könnte mir das auch als gute Idee vorstellen, denke jedoch, dass wir ggf. nicht zum Implementieren von "unwichtigen Upgrades" kommen werden, könnten uns dies aber hierfür im Hinterkopf behalten.

**Comment by pklaschka** [comment]
Noch eine Idee (die ein wenig @daniel1r 's 1. Idee erweitert):

- **Im Endlosmodus bekommt man** (bis man voll gelevelt ist) **vollwertige Upgrades.**
- **Den Endlosmodus schaltet man erst nach allen Leveln** des Kampagnenmoduses frei, sodass man, wenn man den Endboss noch nicht schafft, den Charakter noch weiter leveln kann.
- **Sollte man den Endboss besiegen können,** bevor man alle Level abgeschlossen hat, erscheinen diese als bereits gespielt, sodass man sie nur "nochmal spielen" kann, es sind dann auch alle freigeschaltet.

**Comment by pklaschka** [comment]
# Tipp bez. Kommentaren
Und noch ein kleiner Tipp: Ihr könnt die Kommentare wie ich formatieren, hier einige Hinweise diesbez.:
## "Kommentar-Code"
```markdown
### Dies ist eine Überschrift "dritten Grades" (entsprechend der Anzahl der Rauten davor)

**Dies ist ein fetter Text.**

**Ein neuer Absatz** hat über sich eine Leerzeile
- Listen
- Werden
- Durch
- Bindestriche
- gekennzeichnet
```

## Ergebnis

### Dies ist eine Überschrift "dritten Grades" (entsprechend der Anzahl der Rauten davor)

**Dies ist ein fetter Text.**

**Ein neuer Absatz** hat über sich eine Leerzeile
- Listen
- Werden
- Durch
- Bindestriche
- gekennzeichnet

**Comment by daniel1r** [comment]
@pklaschka den letzten Punkt würde ich rauslassen, meiner Meinung nach ist es besser einfach alle durchgespielten Level als solches anzeigen zu lassen

**Comment by pklaschka** [comment]
@daniel1r Einverstanden, ich habe das jetzt mal in ein Diagramm verpackt:

![image](https://cloud.githubusercontent.com/assets/25147704/22562918/d5b18976-e97e-11e6-915a-4d6037f7d860.png)

**Comment by daniel1r** [comment]
Vorschlag wäre den endbosskampf und den unendlichmodus Vll in die Mitte oder so zu packen, einfach iwo, wo's zur Story passt

**Comment by daniel1r** [comment]
Damit es alles dann auch Sinn ergibt :)

**Comment by pklaschka** [comment]
Die Frage ist dann, ob man die Level dadurch nicht zu einfach macht. Alternativ müsste man bereits die hinteren Level so schwer machen, dass man für sie den Endlosmodus braucht. Auch sollte der Spieler nicht in der Lage sein, sich im ersten Level unendlich leveln zu können. Deshalb sollten die gesammelten Dinge Evtl nur beim 1. Durchspielen des Levels behalten werden?

**Comment by daniel1r** [comment]
Naja keine Ahnung, Könnma ja noch später entscheiden :D

**Comment by M-Lampert** [comment]
Oder man erhöht je weiter man kommt die höhe der währung und xp die man bekommt falls wir sowas einführen sodass man durch die anfangslevel nicht mehr weit kommt.
Zum beispiel anfangs kupfer und 1000 kupfer sind ein silber 
1000 silber ein gold...

**Comment by pklaschka** [comment]
@M-Lampert Das klänge nach einem Plan. Insgesamt können wir ja jetzt einmal grob von diesem Konzept ausgehen, da es - soweit ich das sehe - von allen bisherigen Vorschlägen die funktionierenden Teile miteinbezieht, oder? Wenn ja, würde ich diesbez. morgen noch ein Diagramm erstellen, das Ganze damit ins Reine schreiben und dann in die Wiki stellen.

**Comment by daniel1r** [comment]
Ich würde nur evtl. Nicht so Standard Gold etc. als Währung nehmen, sondern etwas interessanteres/neues

**Comment by pklaschka** [comment]
@daniel1r Gerne, das würde ich aber später planen (am Besten am Montag in der Gruppe, da das auch "Storyrelevanz" hat und nicht mehr wie ein Umbiegen eines nicht funktionierenden zu einem funktionierenden Konzept ein wirkliches "Issue" ist. :smiley:

**Comment by pklaschka** [comment]
@daniel1r Wenn es für dich ok wäre, würde ich ggf. doch bei dem Freischalten des Endlosmodus nach dem letzten regulären Level bleiben, da wir es dann zum "noch weiter leveln, falls nötig" machen könnten sowie der Bosskampf dann wahrscheinlich nicht vor Beenden aller Level stattfindet, sodass wir nicht wieder in die Situation kommen, dass der Spieler die Level halb durchspielt, dann den Boss besiegt, und in den weiteren Leveln feststellen muss, dass diese darauf aufbauen, dass der Boss noch "lebt".
**Diesbezüglich wäre die Story dann,** dass nach dem letzten Level der Charakter in die "Unendliche Welt" reist, um sich weiter auf den Endkampf vorzubereiten :smirk:

**Comment by daniel1r** [comment]
Klar, hab ich nichts dagegen war ja nur ein Vorschlag, solang es dann in die Story eingebaut wird ist alles gut :)

**Comment by pklaschka** [comment]
@daniel1r Wunderbar, dann verpacke ich das in ein verständliches Format und schreibe es in die Wiki. Sobald ich das gemacht habe, schließe ich dann dieses Issue. @daniel1r , @M-Lampert : Vielen Dank für euer Engagement!!!
