### ISSUE TITLE
Unendliches Springen vermeiden

### ISSUE THREAD

**Issue by pklaschka** [pklaschka/RGW-Q11-inf21-16-18-Projekt#6]
_(Nur bevor man das vergisst, schreibe ich es nochmal hier als Issue):_
Zurzeit kann man noch unendlich oft nach oben springen, das müsste man noch korrigieren...

**Comment by M-Lampert** [comment]
Habe das Problem behoben und einen Pull Request gestartet.
Am besten du schaust aber noch einmal drüber @pklaschka

**Comment by pklaschka** [comment]
@M-Lampert 
Perfekt, habe ich gemerged und schließe jetzt das Issue, solltest du den Branch nicht mehr brauchen (für's erste), könntest du ihn bitte löschen?
Danke und VG,
Pablo
