### ISSUE TITLE
Endlosmodus-Bugs

### ISSUE THREAD

**Issue by pklaschka** [pklaschka/RGW-Q11-inf21-16-18-Projekt#81]
- Krokodil spawn auf zu kleinen Inseln -> Krokodil nimmt ganze Insel ein
- 2 Krokodile spawnen ineinander (auf zu kleinen Insel)

@M-Lampert Hier scheint es um den Endlosmodus zu gehen, nachdem ich keine Zeit habe (ich bin an Menüoptimierung, Bestenliste und ähnlichen Geschichten), könntest du das bitte übernehmen?

**Comment by M-Lampert** [comment]
ja kann ich machen

**Comment by pklaschka** [comment]
@M-Lampert
Alles klar, danke.

**Comment by pklaschka** [comment]
#82 Closed this one. 🎉
